{{- if .Values.ingress.enabled -}}
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: AgentEndpoint
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  url: https://{{ .Values.reviewAppID }}.{{ .Values.ingress.domain }}
  upstream:
    url: http://{{ include "app.fullname" $ }}.default:{{ $.Values.service.port }}
{{- end }}
